[package]
name = "branches"
version = "0.1.0"
authors = ["Jason Orendorff <jason.orendorff@gmail.com>"]

[dependencies]
piston = "0.15.1"
piston2d-graphics = "0.11.0"
pistoncore-glutin_window = "0.17.1"
piston2d-opengl_graphics = "0.19.0"
rand = "0.3.14"
